### ISSUE TITLE
so, how to configure the path?

### ISSUE THREAD

**Issue by InternetofThingsprogrammer** [aberonni/open-in-vscode#9]
what does it means?should I download source code first and then I configure the  path of  downloaded files?

**Comment by InternetofThingsprogrammer** [comment]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/26659248/167786872-25926834-20be-4f0d-b0db-33ec51918c8a.png">

**Comment by aberonni** [comment]
Yes, that is correct. For this extension to work, you should have all of your repositories in a single folder. For example, I have all of my repositories in the `/Users/dom/git` folder so that is what I have in that option.

This is how my repositories are stored on my computer:
![image](https://user-images.githubusercontent.com/1260402/171410045-333b47c5-f767-4a9b-a917-5758e6a7e7f0.png)
